[project]
name = "iterate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "attrs>=24.2.0",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
]
